development:
  adapter: mysql
  encoding: utf8
  database: reminders_development
  pool: 5
  timeout: 5000

test: &test
  adapter: mysql
  encoding: utf8
  database: reminders_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: reminders_production
  pool: 5
  timeout: 5000
